### ISSUE TITLE
Incompatible message format compared to amazon-sqs-java-extended-client-lib

### ISSUE THREAD

**Issue by bvinayakumar** [timothymugayi/boto3-sqs-extended-client-lib#7]
The message format produced by "boto3-sqs-extended-client-lib" and "amazon-sqs-java-extended-client-lib" are different if the message size is greater than 256 KB.

**boto3-sqs-extended-client-lib** (JSON object)

e.g.
{"s3BucketName":"some-bucket","s3Key":"some-uuid"}

**amazon-sqs-java-extended-client-lib** (JSON array)

e.g.
["com.amazon.sqs.javamessaging.MessageS3Pointer",{"s3BucketName":"some-bucket","s3Key":"some-uuid"}]

The purpose of raising this issue is to align the message format with Amazon SQS Extended Client Library for Java mentioned in the official documentation.

References:
https://docs.amazonaws.cn/en_us/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-s3-messages.html
https://github.com/awslabs/amazon-sqs-java-extended-client-lib

**Comment by timothymugayi** [comment]
@bvinayakumar thanks for the catch will look into it.

**Comment by Izbitzer** [comment]
I created a PR for this, apologies if anything is missing. I'd be happy to add anything else that would be needed to get it merged.
